[project]
name = "rust-ext-example"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.2",
    "maturin>=1.7.4",
    "msgpack>=1.1.0",
    "numpy>=2.1.2",
    "pip>=24.2",
    "tqdm>=4.66.5",
]
